// app/src/App.tsx
import {BrowserRouter, Route, Routes, } from "react-router-dom";

import CreateRoom from './components/CreateRoom';
import Room from './components/Room';

function App() {
  return (
    <div className="App">
      <BrowserRouter>
        <Routes>
          <Route path="/" element={<CreateRoom />}></Route>
          <Route path="/room/:id" element={<Room/>}></Route>
        </Routes>
      </BrowserRouter>
    </div>
  )
} 

export default App

// packages/web/src/App.svelte
<script>
  import { Router, Route } from 'svelte-routing';

  import Party from './routes/Party.svelte';
  import Home from './routes/Home.svelte';
  import Modal from './components/Modal.svelte';
</script>

<Modal>
  <Router>
    <Route path="/party/:id">
      <Party />
    </Route>
    <Route path="/">
      <Home />
    </Route>
    <Route path="*">Not found</Route>
  </Router>
</Modal>
